name: DEPLOY TO DEDICATED SERVER
on:
  push:
    branches:
    - master
    - CI
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: .
        remote_path: ~/ebird
        remote_host: 171.226.155.174
        remote_port: 22
        remote_user: demo
        remote_key: ${{ secrets.DEPLOY_KEY }}
